name: Deploy to Firebase Hosting to Demo
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    if: '${{ github.repository == portfolio-template-v2 }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build

      - name: Deploy to firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HPAUL_V2 }}'
          channelId: live
          projectId: hpaul-v2
          target: demo
